//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStoreApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProductList
    {
        public int ProductID { get; set; }
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string CategoryName { get; set; }
        public string ProductPhoto { get; set; }
        public string ManufacturerName { get; set; }
        public string SupplierName { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<decimal> ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string UnitName { get; set; }
        public Nullable<decimal> FinalCost { get; set; }
    }
}
